APP_NAME = "Gate AI Quant Professional"
APP_VERSION = "1.0.0"

DEFAULT_CONTRACT = "BTC_USDT"
DEFAULT_INTERVAL = "15m"
DEFAULT_FEE_RATE = 0.0005
DEFAULT_SLIPPAGE_RATE = 0.0002
DEFAULT_RISK_FRACTION = 0.01

SUPPORTED_INTERVALS = ("5m", "15m", "30m", "1h", "4h")
